---
- name: "Install and configure Git"
  hosts: all
  become: true
  vars_files:
    - credentials.yml
  tasks:
    - name: Install Git (Debian/Ubuntu)
      apt:
        name: git
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Git (RHEL/CentOS)
      yum:
        name: git
        state: present
        update_cache: yes
      when: ansible_os_family == "RedHat"

    - name: Set Git username
      command: git config --global user.name "{{ git_username }}"
      become: true

    - name: Set Git email
      command: git config --global user.email "{{ git_email }}"
      become: true
